import { useState } from 'react';
import { Activity, Clock3, Code2, GitBranch, History, Network, Wrench } from 'lucide-react';
import ContextManager from './ContextManager';

export default function AgentPanel({ cwd, model, git, events }: { cwd: string; model: string; git: GitInfo; events: AgentEvent[] }) {
  const [tab, setTab] = useState<'status' | 'history' | 'context'>('status');
  const tools = events.filter(event => event.type === 'tool_call');
  return <aside className={`agent-panel panel ${tab === 'context' ? 'context-open' : ''}`}><div className="agent-tabs"><button className={tab === 'status' ? 'active' : ''} onClick={() => setTab('status')}>AGENT</button><button className={tab === 'context' ? 'active' : ''} onClick={() => setTab('context')}>CONTEXT</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>HISTORY</button></div>
    {tab === 'context' ? <ContextManager /> : tab === 'status' ? <><section><h3><Activity /> SESSION</h3><dl><div><dt>Model</dt><dd>{model}</dd></div><div><dt>Provider</dt><dd>{model.includes('Router') ? 'CCR' : 'Anthropic'}</dd></div><div><dt>Context</dt><dd>由 Context Manager 管理</dd></div><div><dt>Runtime</dt><dd>{events.length ? 'Active' : 'Not started'}</dd></div></dl></section><section><h3><Clock3 /> ACTIVITY</h3><div className="timeline">{events.length ? events.slice(-7).reverse().map((event, index) => <div key={index}><i className={event.type} /><span><b>{event.type.replace('_', ' ')}</b><small>{event.content.slice(0, 54)}</small></span></div>) : <p className="empty">Agent events will appear here</p>}</div></section><section><h3><Wrench /> TOOLS <em>{tools.length}</em></h3>{tools.slice(-4).map((event, index) => <p className="tool" key={index}><Code2 />{event.content.slice(0, 45)}</p>)}</section><section><h3><GitBranch /> GIT</h3><div className="git-branch"><GitBranch />{git.branch}<span>{git.files.length} changes</span></div>{git.files.slice(0, 5).map(file => <div className="git-file" key={file.path}><b>{file.status}</b>{file.path}</div>)}</section><section><h3><Network /> WORKSPACE</h3><p className="path">{cwd}</p></section></> : <section className="history"><h3><History /> EXECUTION HISTORY</h3>{events.slice().reverse().map((event, index) => <div key={index}><span>{new Date(event.timestamp).toLocaleTimeString()}</span><i className={event.type} /><p>{event.content}</p></div>)}</section>}
  </aside>;
}
