import { useMemo, useRef, useState } from 'react';
import { ChevronDown, ChevronRight, File, Folder, FolderOpen, Plus, Search } from 'lucide-react';
import VerticalScrollRail from './VerticalScrollRail';
function Node({ node, level, onOpen }: { node: TreeNode; level: number; onOpen: (node: TreeNode) => void }) { const [open, setOpen] = useState(level < 1); const directory = node.type === 'directory'; return <div><button className="tree-row" style={{ paddingLeft: 8 + level * 14 }} onClick={() => directory ? setOpen(value => !value) : onOpen(node)} onContextMenu={event => { event.preventDefault(); window.studio.fs.menu(node.path); }}>{directory ? open ? <ChevronDown /> : <ChevronRight /> : <span className="chev" />}{directory ? open ? <FolderOpen className="folder" /> : <Folder className="folder" /> : <File className="file" />}<span className="truncate">{node.name}</span></button>{directory && open && node.children?.map(child => <Node key={child.path} node={child} level={level + 1} onOpen={onOpen} />)}</div>; }
export default function Explorer({ cwd, tree, onWorkspace, onTree, onFile }: { cwd: string; tree: TreeNode[]; onWorkspace: (value: { cwd: string; tree: TreeNode[] }) => void; onTree: (value: TreeNode[]) => void; onFile: (node: TreeNode) => void }) {
  const [query, setQuery] = useState('');
  const treePane = useRef<HTMLDivElement>(null);
  const filtered = useMemo(() => { const walk = (nodes: TreeNode[]): TreeNode[] => nodes.flatMap(node => { const children = node.children ? walk(node.children) : []; return node.name.toLowerCase().includes(query.toLowerCase()) || children.length ? [{ ...node, children }] : []; }); return query ? walk(tree) : tree; }, [query, tree]);
  const openWorkspace = async () => { const value = await window.studio.workspace.open(); if (value) onWorkspace(value); };
  const create = async (type: 'file' | 'directory') => { const name = prompt(type === 'file' ? '新建文件名' : '新建目录名'); if (name && cwd) onTree(await window.studio.fs.create(`${cwd}\\${name}`, type)); };
  return <aside className="explorer panel"><div className="section-title"><span>EXPLORER</span><div><button title="新建文件" onClick={() => create('file')}><Plus /></button><button title="打开文件夹" onClick={openWorkspace}><FolderOpen /></button></div></div><button className="workspace" title={cwd} onClick={openWorkspace}><ChevronDown /><strong>{cwd.split(/[\\/]/).pop() || '打开文件夹'}</strong></button><div className="search"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索文件" /></div><div className="tree-shell"><div className="tree" ref={treePane}>{filtered.map(node => <Node key={node.path} node={node} level={0} onOpen={onFile} />)}</div><VerticalScrollRail target={treePane} /></div><div className="recent"><div className="section-title">CURRENT WORKSPACE</div><button title={cwd} onClick={openWorkspace}>{cwd || '选择工作区'}</button></div></aside>;
}
