import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
type Metrics = { top: number; height: number; enabled: boolean };
export default function VerticalScrollRail({ target }: { target: React.RefObject<HTMLElement> }) {
  const track = useRef<HTMLDivElement>(null); const [metrics, setMetrics] = useState<Metrics>({ top: 0, height: 40, enabled: false });
  const dragState = useRef<{ pointerId: number; startY: number; startScroll: number; maxScroll: number; usable: number }>();
  const measure = useCallback(() => { const element = target.current, rail = track.current; if (!element || !rail) return; const trackHeight = rail.clientHeight; const enabled = element.scrollHeight > element.clientHeight + 1; const height = enabled ? Math.max(40, trackHeight * element.clientHeight / element.scrollHeight) : trackHeight; const maxTop = Math.max(0, trackHeight - height); const maxScroll = Math.max(1, element.scrollHeight - element.clientHeight); setMetrics({ top: enabled ? maxTop * element.scrollTop / maxScroll : 0, height, enabled }); }, [target]);
  useLayoutEffect(() => { const element = target.current; if (!element) return; const resize = new ResizeObserver(measure); const mutation = new MutationObserver(measure); resize.observe(element); mutation.observe(element, { childList: true, subtree: true, characterData: true }); element.addEventListener('scroll', measure, { passive: true }); measure(); return () => { resize.disconnect(); mutation.disconnect(); element.removeEventListener('scroll', measure); }; }, [measure, target]);
  useEffect(() => { measure(); }, [measure]);
  const move = (amount: number) => target.current?.scrollBy({ top: amount, behavior: 'smooth' });
  const beginDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (!metrics.enabled || !target.current || !track.current) return; event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); dragState.current = { pointerId: event.pointerId, startY: event.clientY, startScroll: target.current.scrollTop, maxScroll: target.current.scrollHeight - target.current.clientHeight, usable: Math.max(1, track.current.clientHeight - metrics.height) }; };
  const continueDrag = (event: React.PointerEvent<HTMLDivElement>) => { const state = dragState.current, pane = target.current; if (!state || state.pointerId !== event.pointerId || !pane) return; pane.scrollTop = state.startScroll + (event.clientY - state.startY) * state.maxScroll / state.usable; };
  const endDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (dragState.current?.pointerId !== event.pointerId) return; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); dragState.current = undefined; };
  return <div className={`vertical-scroll-rail ${metrics.enabled ? 'enabled' : 'disabled'}`} aria-label="纵向滚动条"><button aria-label="向上滚动" onClick={() => move(-180)}><ChevronUp /></button><div className="vertical-scroll-track" ref={track} onClick={event => { const pane = target.current; if (pane && event.target === event.currentTarget) move(event.clientY < event.currentTarget.getBoundingClientRect().top + metrics.top ? -pane.clientHeight * .8 : pane.clientHeight * .8); }}><div className="vertical-scroll-thumb" style={{ height: metrics.height, transform: `translateY(${metrics.top}px)` }} onPointerDown={beginDrag} onPointerMove={continueDrag} onPointerUp={endDrag} onPointerCancel={endDrag} /></div><button aria-label="向下滚动" onClick={() => move(180)}><ChevronDown /></button></div>;
}
